import {levels} from '../levels/levels.js';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
export class GameEngine{
 constructor(ui,progress){this.ui=ui;this.progress=progress;this.level=1;this.running=false}
 attachBlockly(b){this.blockly=b}
 load(n){if(n>this.progress.data.unlockedLevel)return;this.level=n;this.config=levels[n];this.state={level:n,robot:{x:this.config.start[0],y:this.config.start[1],direction:'right'},resources:this.config.resources.map(([type,x,y],i)=>({id:i,type,x,y,collected:false})),obstacles:this.config.obstacles||[],variables:this.config.vars?{...this.config.vars}:{},completed:false,real:{'болтики':0,'топливо':0},repaired:[],path:null};this.running=false;this.ui.hintIndex=0;this.blockly.load(n);this.ui.renderAll()}
 async move(dx,dy){if(this.running||!this.config.manual)return;const {robot:r}=this.state,x=r.x+dx,y=r.y+dy;if(x<0||x>6||y<0||y>5||this.state.obstacles.some(o=>o[0]===x&&o[1]===y))return this.ui.toast('Там путь закрыт!','warn');r.direction=dx<0?'left':dx>0?'right':r.direction;r.x=x;r.y=y;this.ui.renderBoard();await this.collect();this.check()}
 async collect(){const r=this.state.resources.find(a=>!a.collected&&a.x===this.state.robot.x&&a.y===this.state.robot.y);if(!r)return;r.collected=true;const key=r.type==='bolt'?'болтики':'топливо';this.state.real[key]++;this.ui.animateTransfer(r.type,key);if(this.level===1)this.setVariable(key,this.state.variables[key]+1);else await this.blockly.runtime.emit(r.type==='bolt'?'collectBolt':'collectFuel');this.ui.renderBoard()}
 setVariable(name,value){const old=this.state.variables[name];this.state.variables[name]=value;this.ui.renderVariables(name,old)}
 createVariable(name){if(!(name in this.state.variables)){this.state.variables[name]=undefined;this.ui.renderVariables(name);this.ui.toast(`Переменная «${name}» создана. Теперь задай ему значение.`,'ok')}}
 syncVariables(){if(this.level!==3||!this.blockly.workspace)return;for(const v of this.blockly.workspace.getAllVariables())if(['болтики','топливо'].includes(v.name))this.createVariable(v.name)}
 noteMissing(n){this.ui.toast(`Робот не нашёл переменную ${n}. Сначала создай переменную.`,'error')}
 async run(){if(this.running||this.level===1)return;this.resetRun();this.running=true;this.ui.setRunning(true);this.blockly.runtime.compile();await this.blockly.runtime.emit('start');if(this.level===5){for(const p of this.config.route){await this.step(p);await this.collect()}await this.blockly.runtime.emit('reachFork');if(!this.state.path)this.ui.toast('На развилке робот не получил команду пути.','error');}else{for(const p of this.config.route){await this.step(p);await this.collect()}if(this.level===4){for(const st of this.config.stations){await this.blockly.runtime.emit('reachStation',{cost:-st[1]});this.state.repaired.push(st[0]);this.ui.renderAll();await wait(350)}}}this.running=false;this.ui.setRunning(false);this.check(true)}
 resetRun(){this.state.robot={x:this.config.start[0],y:this.config.start[1],direction:'right'};this.state.resources.forEach(r=>r.collected=false);this.state.real={'болтики':0,'топливо':0};this.state.repaired=[];this.state.path=null;if(this.config.vars)this.state.variables={...this.config.vars};else for(const k in this.state.variables)this.state.variables[k]=undefined;this.ui.renderAll()}
 async step([x,y]){this.state.robot.x=x;this.state.robot.y=y;this.ui.renderBoard();await wait(420)}
 async choosePath(path){this.state.path=path;if(path==='short'){if((this.state.variables['топливо']??0)>=3)this.setVariable('топливо',this.state.variables['топливо']-3);else return this.ui.toast('Не хватает топлива для короткого пути!','error')}this.ui.toast(path==='short'?'⚡ Короткий путь открыт!':'🌙 Робот выбрал длинный путь.','ok');await wait(500)}
 check(after=false){if(this.level===1&&!this.state.resources.some(r=>!r.collected))return this.finish('В программировании такие шкалы называются переменными. Переменная имеет имя и хранит значение.');if(!after)return;const v=this.state.variables,r=this.state.real;if(this.level===2||this.level===3){if(!('болтики'in v)||!('топливо'in v))return this.ui.toast(`Робот не нашёл переменную ${!('болтики'in v)?'болтики':'топливо'}. Сначала создай переменную с таким именем.`,'error');if(v['болтики']===undefined||v['топливо']===undefined)return this.ui.toast('Переменная создана, но в ней пока «?». Установи значение 0 при старте.','error');if(v['болтики']!==r['болтики'])return this.diagnose('болтики',r['болтики'],v['болтики']);if(v['топливо']!==r['топливо'])return this.diagnose('топливо',r['топливо'],v['топливо']);return this.finish('Отлично! Русские имена переменных связали события с правильными значениями.')}if(this.level===4){if(v['болтики']!==r['болтики']-5)return this.ui.toast(`После 7 находок и ремонта должно остаться 2, а «болтики» = ${v['болтики']}. Проверь вычитание стоимости.`,'error');return this.finish('Обе станции работают! Переменная умеет и расти, и уменьшаться.')}if(this.level===5){if(!this.state.path)return;if(this.state.path==='short'&&v['топливо']===0)return this.finish('База достигнута! Ты прочитал переменную «топливо» в условии и потратил топливо.');if(this.state.path==='long')return this.ui.toast('Топлива было 3 — условие должно открыть короткий путь.','error')}}
 diagnose(k,real,val){const other=k==='болтики'?'топливо':'болтики';if(val===this.state.real[other])return this.ui.toast(`Похоже, ресурсы изменяют «${k}». Проверь, куда нужно записывать «${other}».`,'error');if(val>real)return this.ui.toast(`Робот собрал ${real}, но «${k}» = ${val}. Значение изменяется слишком много раз.`,'error');this.ui.toast(`Робот собрал ${real}, но «${k}» = ${val}. Проверь увеличение при каждой находке.`,'error')}
 finish(text){this.state.completed=true;this.progress.complete(this.level);this.ui.renderLevels();this.ui.modal(text,this.level<5)}
}
