export class UIManager{
 constructor(){this.hintIndex=0}
 bind(engine,blockly,progress){this.engine=engine;this.blockly=blockly;this.progress=progress;document.querySelector('#run').onclick=()=>engine.run();document.querySelector('#reset').onclick=()=>engine.load(engine.level);document.querySelector('#clear').onclick=()=>blockly.clear();document.querySelector('#hint').onclick=()=>this.hint();document.querySelector('#wipe').onclick=()=>confirm('Стереть весь прогресс?')&&progress.reset();document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const [x,y]=b.dataset.move.split(',').map(Number);engine.move(x,y)});addEventListener('keydown',e=>{const d={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[e.key];if(d){e.preventDefault();engine.move(...d)}})}
 renderAll(){const c=this.engine.config;document.querySelector('#levelTitle').textContent=`Уровень ${this.engine.level} · ${c.title}`;document.querySelector('#task').textContent=c.task;document.body.classList.toggle('manual',!!c.manual);this.renderLevels();this.renderBoard();this.renderVariables();}
 renderLevels(){const p=this.progress.data;document.querySelector('#levels').innerHTML=[1,2,3,4,5].map(n=>`<button class="level ${n===this.engine.level?'active':''}" data-level="${n}" ${n>p.unlockedLevel?'disabled':''}>${p.completedLevels.includes(n)?'✓ ':''}${n}</button>`).join('');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>this.engine.load(+b.dataset.level))}
 renderBoard(){const s=this.engine.state;document.querySelector('#board').innerHTML=Array.from({length:42},(_,i)=>{const x=i%7,y=Math.floor(i/7),r=s.resources.find(a=>!a.collected&&a.x===x&&a.y===y),ob=s.obstacles.some(o=>o[0]===x&&o[1]===y),robot=s.robot.x===x&&s.robot.y===y,station=s.config;return `<div class="cell ${ob?'obstacle':''}">${r?`<span class="resource">${r.type==='bolt'?'🔩':'⛽'}</span>`:''}${robot?'<span class="robot">🤖</span>':''}${this.engine.level===5&&x===3&&y===3?'<span class="fork">⑂</span>':''}${this.engine.level===4&&x===6&&y===2?'<span class="station">🛰️</span>':''}</div>`}).join('')}
 renderVariables(changed,old){const v=this.engine.state.variables,keys=Object.keys(v);document.querySelector('#variables').innerHTML=keys.length?keys.map(k=>`<div class="memory ${changed===k?'pulse':''}"><span class="chip">MEM</span><b>${k}</b><strong>${v[k]===undefined?'?':v[k]}</strong>${changed===k&&old!==undefined?`<small>${old} → ${v[k]}</small>`:''}</div>`).join(''):'<div class="empty">🧰<br>Контейнеров пока нет</div>'}
 animateTransfer(type,key){this.toast(`${type==='bolt'?'🔩 Болтик':'⛽ Топливо'} → контейнер ${key}`,'collect')}
 toast(t,type=''){const el=document.querySelector('#toast');el.textContent=t;el.className=`toast show ${type}`;clearTimeout(this.tt);this.tt=setTimeout(()=>el.classList.remove('show'),4200)}
 hint(){const h=this.engine.config.hints;this.toast(`💡 ${h[Math.min(this.hintIndex++,h.length-1)]}`,'hint')}
 setRunning(x){document.querySelector('#run').disabled=x;document.querySelector('#run').textContent=x?'Выполняю…':'▶ Запустить'}
 modal(text,next){const m=document.querySelector('#modal');m.innerHTML=`<div><span class="trophy">🏆</span><h2>Уровень пройден!</h2><p>${text}</p><button id="continue">${next?'Следующий уровень →':'Я освоил переменные!'}</button></div>`;m.classList.add('show');document.querySelector('#continue').onclick=()=>{m.classList.remove('show');if(next)this.engine.load(this.engine.level+1)}}
}
