const sleep=ms=>new Promise(r=>setTimeout(r,ms));
export class BlocklyRuntime{
 constructor(manager,engine){this.manager=manager;this.engine=engine;this.handlers={};}
 compile(){this.handlers={start:[],collectBolt:[],collectFuel:[],reachStation:[],reachFork:[]};const map={event_start:'start',event_bolt:'collectBolt',event_fuel:'collectFuel',event_station:'reachStation',event_fork:'reachFork'};for(const top of this.manager.workspace.getTopBlocks(true)){if(map[top.type])this.handlers[map[top.type]].push(...this.statements(top.getNextBlock()));}return this.handlers}
 statements(block){const out=[];for(let b=block;b;b=b.getNextBlock()){if(b.type==='change_var'||b.type==='set_var')out.push({type:b.type==='change_var'?'CHANGE':'SET',variable:b.getFieldValue('VAR'),value:this.value(b.getInputTargetBlock('VALUE')),blockId:b.id});else if(b.type==='robot_if')out.push({type:'IF',condition:this.condition(b.getInputTargetBlock('IF0')),then:this.statements(b.getInputTargetBlock('DO0')),otherwise:this.statements(b.getInputTargetBlock('ELSE')),blockId:b.id});else if(b.type==='short_path'||b.type==='long_path')out.push({type:'PATH',path:b.type==='short_path'?'short':'long',blockId:b.id});}return out}
 value(b){if(!b)return 0;if(b.type==='math_number')return Number(b.getFieldValue('NUM'));if(b.type==='station_cost')return 'stationCost';if(b.type==='variables_get')return {var:b.getFieldValue('VAR')};return 0}
 condition(b){if(!b||b.type!=='logic_compare')return ()=>false;const a=this.value(b.getInputTargetBlock('A')),c=this.value(b.getInputTargetBlock('B')),op=b.getFieldValue('OP');return ()=>{const x=typeof a==='object'?this.engine.state.variables[a.var]:a,y=typeof c==='object'?this.engine.state.variables[c.var]:c;return op==='GTE'?x>=y:op==='GT'?x>y:op==='EQ'?x===y:x<y}}
 async emit(name,ctx={}){for(const command of this.handlers[name]||[])await this.run(command,ctx)}
 async run(c,ctx){this.manager.highlight(c.blockId);await sleep(430);const s=this.engine.state;if(c.type==='SET'||c.type==='CHANGE'){if(!(c.variable in s.variables))return this.engine.noteMissing(c.variable);let v=c.value==='stationCost'?ctx.cost:c.value;if(c.type==='CHANGE')v=(s.variables[c.variable]??0)+v;this.engine.setVariable(c.variable,v)}else if(c.type==='IF'){for(const x of (c.condition()?c.then:c.otherwise))await this.run(x,ctx)}else if(c.type==='PATH')await this.engine.choosePath(c.path);}
}
